### ISSUE TITLE
Get all the branches & get all the tags

### ISSUE THREAD

**Issue by charJe** [Shinmera/legit#9]
`git-branch` seems to be a low level function, and when called without arguments it prints the branches exactly as `git branch` does. Is there some way to get all the branches as a first class data structure? Same question for tags.

**Comment by Shinmera** [comment]
Not as it stands.

**Comment by charJe** [comment]
Alright, would you be open to a pull request that has a higher level `branch` command that takes a gir repository rather than relying on the current working directory. I guess it would just parse the output of `git-branch`.

**Comment by Shinmera** [comment]
Sure, same as the other stuff in the `repository` file.
